# Generated by Django 5.1.6 on 2025-03-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_remove_item_dostupno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='naziv',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='kategorija',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='slika',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='cijena',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='naziv',
            new_name='title',
        ),
    ]
