# Generated by Django 5.1.6 on 2025-03-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_rename_content_conversationmessage_sadržaj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='sadržaj',
            new_name='content',
        ),
    ]
